name: tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 25.x
        uses: actions/setup-node@v4
        with:
          node-version: 25
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-nodejs-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nodejs-
      - name: Install deps
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Type check
        run: npm run check
      - name: Build (Chrome)
        run: npm run build
      - name: Build (Firefox)
        run: npm run build:firefox
